# -*- coding: utf-8 -*-
"""movie recommended system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pHiK5hW8rWEJLwJ3ihR7O4Y0FIvBRMo7
"""



"""#Movie Recommendation System

**Recommender System** is a system that seeks to predict or filter preferences according to the user's choices. Recommender systems are utilized in a variety of areas including movies, music, news, books, research articles, search queries, social tags, and products in general. Recommender systems produce a list of recommendations in any of the two ways-

**Collaborative filtering:** Collaborative filtering approaches build a model from the user's past behavior (i.e. items purchased or searched by the user) as well as similar decisions made by other users. This model is then used to predict items (or ratings for items) that users may have an interest in

**Content-based filtering:** Content-based filtering approaches uses a series of discrete characteristics of an item in order to recommend additional items with similar properties. Content-based filtering methods are totally based on a description of the item and a profile of the user's preferences. It recommends items based on the user's past preferences. Let's develop a basic recommendation system using Python and Pandas.

Let's develop a basic recommendation system by suggesting items that are most similar to a particular item, in this case, movies. It just tells what movies/items are most similar to the user's movie choice.

# import Library
"""

import pandas as pd

import numpy as np

"""# import Dataset"""

df=pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Movies%20Recommendation.csv')

df.head()

df.info()

df.shape

df.columns

"""# Get feature selection"""

df_features=df[[ 'Movie_Genre','Movie_Keywords','Movie_Tagline', 'Movie_Cast','Movie_Director']].fillna('')

df_features.shape

df_features

X= df_features["Movie_Genre"] +''+df_features["Movie_Director"]+''+df_features["Movie_Keywords"]+''+df_features['Movie_Tagline']+''+df_features["Movie_Cast"]

X

X.shape

"""# Get Feature text conversion to tokens"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()

X=tfidf.fit_transform(X)

X.shape

print(X)

"""# Get similarity Score using Cosine Simiarity"""

from sklearn.metrics.pairwise import cosine_similarity

 similarity_Score =cosine_similarity(X)

similarity_Score

similarity_Score.shape

"""# Get Movie Name as input from User and Validate for Closet spelling"""

favourite_movie_name=input('Enter your favourite movie name: ')

All_movies_title_list=df['Movie_Title'].tolist()

import difflib

movie_recommendation=difflib.get_close_matches(favourite_movie_name,All_movies_title_list)
print(movie_recommendation)

close_match=movie_recommendation[0]
print(close_match)

index_of_close_match_movie=df[df.Movie_Title==close_match]['Movie_ID'].values[0]
print(index_of_close_match_movie)

recommendation_score=list(enumerate(similarity_Score[index_of_close_match_movie]))
print(recommendation_score)

len(recommendation_score)

"""# Get All movies sort based on Recommendation Score wrt Favourite movie"""

sorted_similar_movies=sorted(recommendation_score,key=lambda X:X[1],reverse=True)
print(sorted_similar_movies)

print('top 30 movies suggested for you : \n')
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=df[df.index==index]['Movie_Title'].values[0]
  if (i<31):
    print(i,'.',title_from_index)
    i+=1

Movie_Name = input("Enter your favourite movie name : ")

list_of_all_titles= df['Movie_Title'].tolist()

Find_Close_Match= difflib.get_close_matches (Movie_Name, list_of_all_titles)
Close_Match = Find_Close_Match[0]

index_of_Movie=df[df.Movie_Title== Close_Match]['Movie_ID'].values[0]

Recommendation_Score = list(enumerate(similarity_Score[index_of_Movie]))

sorted_similar_movies=sorted(Recommendation_Score, key = lambda X:X[1], reverse = True)

print("Top 10 Movies suggested for you : \n")

i=1

for movie in sorted_similar_movies:
  index =movie[0]

  title_from_index = df [df.Movie_ID==index]['Movie_Title'].values

  if (i<11):

      print(i,'.',title_from_index)
      i+=1

